#Instalacion de una imagen 3.8.1 con maven y java 15
FROM maven:3.8.1-adoptopenjdk-15

#Copia del repositorio del proyecto
RUN git clone http://*your repository*

#Crea una carpeta para el volumen (persistencia de datos)

RUN mkdir /jar

#Creacion del volumen
VOLUME /jar

WORKDIR /backend

#Cambio a la rama develop, ya que la rama por defecto es la master
RUN git checkout develop

#Cambio de directorio para ejecutar el comando que compila y guarda la compilación de los distintos módulos en un volumen
WORKDIR /backend/microservices/java

CMD sh -c "mvn package; find /backend/microservices/java -name "*.jar" -exec cp '{}' /jar \;"
